/**
 * Protocol v1 — message types and runtime validation
 *
 * This file is the SINGLE source of truth for the WebSocket message contract
 * between the StablePiggy Napoleon Game Assistant Foundry module and the
 * relay service. Both packages import from here. Adding a new message kind
 * requires updating this file and implementing handlers in BOTH the module
 * (../scripts) and the relay (../relay/src). TypeScript's discriminated
 * union narrowing will catch any drift between them at compile time.
 *
 * Wire format: each message is a single JSON object matching the
 * `ProtocolMessage` discriminated union. The union is keyed on `kind` so
 * handlers can narrow the type with a `switch (msg.kind)` statement.
 *
 * Runtime validation: the relay calls `validateMessage(input)` on every
 * inbound WebSocket frame after JSON parsing. Invalid messages throw a
 * `ProtocolError` with a specific code; the relay catches these and sends
 * back an `error` message with the same code and the correlation id of the
 * offending message.
 *
 * See planning/phase2-tier1-plan.md §3 for the full protocol specification.
 */

// ============================================================================
// Protocol version
// ============================================================================

/**
 * The current protocol version. Both the module and the relay declare this
 * version on connect via `client.hello` / `relay.welcome`. Version mismatches
 * are fatal — the relay rejects the connection with a `protocol_mismatch`
 * error, and the module shows a "please update" notice in its settings panel.
 */
export const PROTOCOL_VERSION = 1 as const;

/**
 * Type alias for the protocol version constant.
 */
export type ProtocolVersion = typeof PROTOCOL_VERSION;

// ============================================================================
// Error codes
// ============================================================================

/**
 * All possible error codes that can appear in a protocol `error` message or
 * be thrown as a `ProtocolError`. These are the stable public codes the
 * module and the relay agree on — adding a new code is a protocol addition
 * that requires updating both sides.
 */
export type ErrorCode =
  /** Authentication token missing, malformed, or not recognized. */
  | "unauthorized"
  /** Message has a `v` field that does not equal PROTOCOL_VERSION. */
  | "protocol_mismatch"
  /** Message envelope or payload failed structural validation. */
  | "validation_failed"
  /** Message `kind` is not a known MessageKind. */
  | "unknown_kind"
  /** Client is sending too many messages too quickly. */
  | "rate_limited"
  /** The AI backend cannot be reached by the relay. */
  | "backend_unreachable"
  /** The AI backend returned an error response. */
  | "backend_error"
  /** An unexpected error occurred on the relay; details in the message. */
  | "internal_error";

/**
 * Structured protocol error. Thrown by `validateMessage()` and by relay
 * handlers when they need to report a failure back to the client as a
 * protocol `error` message. The `correlationId` field points at the message
 * that caused the error, if any.
 */
export class ProtocolError extends Error {
  public override readonly name = "ProtocolError" as const;

  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly correlationId?: string
  ) {
    super(message);
  }
}

// ============================================================================
// Message kinds
// ============================================================================

/**
 * All possible message kinds in protocol v1. This is the discriminator for
 * the `ProtocolMessage` union — `switch (msg.kind)` narrows the payload type
 * automatically.
 */
export type MessageKind =
  | "client.hello"
  | "relay.welcome"
  | "client.query"
  | "client.session_event"
  | "client.data_upload_ack"
  | "client.world_save_request"
  | "backend.chat.create"
  | "backend.actor.create"
  | "backend.actor.update"
  | "backend.journal.create"
  | "backend.rolltable.create"
  | "backend.scene.create"
  | "backend.scene.update"
  | "backend.token.create"
  | "backend.wall.create"
  | "backend.light.create"
  | "backend.data.upload"
  | "ping"
  | "pong"
  | "error";

// ============================================================================
// Envelope
// ============================================================================

/**
 * Common envelope for all protocol messages. Every message on the wire has
 * these fields plus a kind-specific `payload`. The generic parameter `K`
 * narrows the payload type when used via the `ProtocolMessage` union.
 */
interface BaseMessage<K extends MessageKind, P> {
  /** Protocol version. Always equals `PROTOCOL_VERSION`. */
  readonly v: ProtocolVersion;
  /** 16-character alphanumeric message ID, generated by the sender. */
  readonly id: string;
  /** Sender's clock at message creation (Unix epoch milliseconds). */
  readonly ts: number;
  /** Message type discriminator. */
  readonly kind: K;
  /** Kind-specific payload. */
  readonly payload: P;
}

// ============================================================================
// Client capability declaration
// ============================================================================

/**
 * Capabilities declared by the Foundry module in its `client.hello` message.
 * The backend uses these to gate features — a `backend.actor.create` will
 * only be sent to clients that declare `actorCreate: true`.
 *
 * Tier 1 has a fixed set of capabilities. Tier 2+ adds `combatStateRead`,
 * `tokenMove`, `playlistControl`, etc.
 */
export interface ClientCapabilities {
  /** Module can render injected chat messages via `backend.chat.create`. */
  readonly chatCreate: boolean;
  /** Module can create actors via `backend.actor.create`. */
  readonly actorCreate: boolean;
  /** Module can update actors via `backend.actor.update`. */
  readonly actorUpdate?: boolean;
  /** Module can create journal entries via `backend.journal.create`. */
  readonly journalCreate: boolean;
  /** Module can create roll tables via `backend.rolltable.create`. */
  readonly rolltableCreate?: boolean;
  /** Module can create scenes via `backend.scene.create`. */
  readonly sceneCreate?: boolean;
  /** Module can place tokens on scenes via `backend.token.create`. */
  readonly tokenCreate?: boolean;
  /** Module can place walls on scenes via `backend.wall.create` (V2 Phase 3). */
  readonly wallCreate?: boolean;
  /** Module can place ambient lights on scenes via `backend.light.create` (V2 Phase 3). */
  readonly lightCreate?: boolean;
  /** Module can apply scene-level updates via `backend.scene.update` (V2 Phase 3). */
  readonly sceneUpdate?: boolean;
  /** Module can persist Barn files to Foundry Data via `backend.data.upload` (Phase B.4 durability). */
  readonly dataUpload?: boolean;
  /** Foundry system module ID, e.g. "pf2e". */
  readonly systemId: string;
  /** Foundry system module version, e.g. "7.12.1". */
  readonly systemVersion: string;
  /** Foundry core version, e.g. "13.351". */
  readonly foundryVersion: string;
}

// ============================================================================
// Payload interfaces
// ============================================================================

/**
 * Payload for `client.hello`. The module sends this as the first message
 * after the WebSocket connection opens. The relay verifies the protocol
 * version AND the `authToken` before promoting the connection from pending
 * to authenticated, and responds with `relay.welcome` on success or an
 * `error` message (followed by close 1008) on failure.
 *
 * **Authentication model.** Browsers cannot set custom HTTP headers on the
 * WebSocket upgrade request, so the relay cannot read an `Authorization`
 * header from the upgrade handshake. Instead, authentication is carried
 * inline as `authToken` in the first protocol message. The relay accepts
 * all upgrades, starts a short grace timer, and verifies the token when
 * the hello arrives. The relay has two auth modes selected per-token by
 * prefix:
 *
 * - Tokens beginning with `dv-` are StablePiggy API keys. The relay
 *   forwards them to the backend's identity endpoint to resolve the real
 *   `identityId` for the GM, which unlocks vault, campaign memory, and
 *   metering on every subsequent query in this connection.
 * - Any other non-empty string is treated as a shared secret and compared
 *   against the relay's configured `RELAY_SHARED_SECRET`. On success the
 *   relay constructs a synthetic anonymous identity (`anon:<worldId>:
 *   <gmUserId>`) and uses it for backend calls. Anonymous identities
 *   have no vault access, no persistent memory, and no metering — the
 *   upgrade path to an account is literally just "paste a dv- key here
 *   instead."
 *
 * Hosted relay instances can set `RELAY_REQUIRE_API_KEY=true` to reject
 * non-`dv-` tokens at hello time (so only StablePiggy account holders can
 * use the shared hosted relay). Self-hosted relays leave that flag off.
 */
export interface ClientHelloPayload {
  /** Protocol version the module speaks (should equal `PROTOCOL_VERSION`). */
  readonly protocolVersion: ProtocolVersion;
  /**
   * Relay auth token. Either a StablePiggy API key (starts with `dv-`) or
   * an arbitrary shared secret matching the relay's `RELAY_SHARED_SECRET`.
   * The relay closes the connection with code 1008 if this token is
   * missing, malformed, or fails verification.
   */
  readonly authToken: string;
  /** Foundry world ID the module is running in. */
  readonly worldId: string;
  /** Foundry user ID of the GM running the module (must be a GM). */
  readonly gmUserId: string;
  /**
   * True if this GM is the designated primary GM for multi-GM worlds. Tier 1
   * enforces single primary GM — if a second GM connects with `isPrimaryGM:
   * true`, the relay rejects the second connection.
   */
  readonly isPrimaryGM: boolean;
  /** Module version string, e.g. "0.1.0". */
  readonly moduleVersion: string;
  /** Declared client capabilities. See `ClientCapabilities`. */
  readonly capabilities: ClientCapabilities;
}

/**
 * Payload for `relay.welcome`. The relay sends this in response to a valid
 * `client.hello`. The module uses `backendAvailable` to decide whether to
 * show a "waiting for backend" indicator in the settings panel.
 */
export interface RelayWelcomePayload {
  /** Protocol version the relay speaks. */
  readonly protocolVersion: ProtocolVersion;
  /** Relay software version string, e.g. "0.1.0". */
  readonly relayVersion: string;
  /**
   * Whether the relay can currently reach the StablePiggy AI backend. If
   * false, the module can still send `client.query` messages but they will
   * be rejected with a `backend_unreachable` error.
   */
  readonly backendAvailable: boolean;
  /**
   * Relay's server clock at welcome send time. Used by the module for clock
   * skew debugging.
   */
  readonly serverTime: number;
}

/**
 * Optional structured context attached to a `client.query`. Tier 1 passes
 * empty or minimal context; Tier 2 starts populating the scene and combat
 * fields for tactical assist features.
 */
/**
 * Scene dimensional data (V2 Phase 3 addition). Foundry's scene
 * coordinate space includes a padding ring around the image, so
 * pixel (0, 0) in scene space is the top-left of the PADDED canvas,
 * NOT the top-left of the visible background image. Napoleon needs
 * the image's actual bounds (sceneX/sceneY/sceneWidth/sceneHeight
 * from Foundry's scene.dimensions) to place walls, lights, and
 * tokens on the map instead of in the padding margin.
 *
 * All values in scene pixels. Sourced from `game.scenes.current.dimensions`
 * which Foundry V13 computes per scene.
 */
export interface SceneDimensions {
  /** X pixel where the background image starts inside the padded canvas. */
  readonly imageX: number;
  /** Y pixel where the background image starts inside the padded canvas. */
  readonly imageY: number;
  /** Image width in pixels. */
  readonly imageWidth: number;
  /** Image height in pixels. */
  readonly imageHeight: number;
  /** Full padded canvas width (image + padding on both sides). */
  readonly totalWidth: number;
  /** Full padded canvas height. */
  readonly totalHeight: number;
  /** Grid cell size in pixels. */
  readonly gridSize: number;
}

/**
 * V2 Phase 4 — Module-Aware Napoleon. Compact summaries of the Foundry
 * world's existing content so Napoleon can reference module-provided
 * actors / scenes / journals / items by NAME instead of hallucinating
 * duplicates. Module enumerates this on every `client.query` send when
 * a Foundry session is connected; the backend injects a "## Current
 * world contents" block into the composed user message.
 *
 * Summaries only — full documents stay out of the prompt budget.
 * Phase 4b will add deep-read tools that fetch a single full document
 * on demand when Napoleon needs more than a summary.
 *
 * Per-type entry caps are enforced module-side at enumeration time
 * (defaults: actors 300, scenes 75, journals 250, items 200, modules
 * 50; configurable per spec §10 Q4). Folder names are included so
 * Napoleon can scope answers to a chapter / area folder.
 */
export interface WorldContentActor {
  readonly id: string;
  readonly name: string;
  /** Foundry actor type — 'character' | 'npc' | 'loot' | 'vehicle' | 'hazard' | etc. */
  readonly type: string;
  readonly level?: number;
  readonly folder?: string;
}

export interface WorldContentScene {
  readonly id: string;
  readonly name: string;
  /** Whether this scene is the currently-viewed/active scene. */
  readonly active: boolean;
  readonly folder?: string;
}

export interface WorldContentJournal {
  readonly id: string;
  readonly name: string;
  readonly folder?: string;
  readonly pageCount?: number;
}

export interface WorldContentItem {
  readonly id: string;
  readonly name: string;
  /** Foundry item type — 'weapon' | 'armor' | 'consumable' | etc. */
  readonly type: string;
  readonly folder?: string;
}

export interface WorldContentModule {
  /** Foundry manifest id — e.g. `pf2e.abomination-vaults`. */
  readonly id: string;
  readonly title: string;
  readonly active: boolean;
}

export interface WorldContent {
  readonly actors: readonly WorldContentActor[];
  readonly scenes: readonly WorldContentScene[];
  readonly journals: readonly WorldContentJournal[];
  readonly items: readonly WorldContentItem[];
  readonly modules: readonly WorldContentModule[];
}

export interface QueryContext {
  /** Currently-active scene ID in Foundry, or null if none. */
  readonly sceneId: string | null;
  /**
   * Currently-active scene name in Foundry (V2 Phase 3 addition). When
   * present, the backend injects it into the composed user message so
   * Napoleon knows which scene the GM is looking at — required for
   * scene-modification intents ("add walls here") to target the right
   * scene instead of the last one Napoleon remembers.
   */
  readonly sceneName?: string | null;
  /**
   * Currently-active scene's computed dimensions (V2 Phase 3). Lets
   * the backend tell Napoleon where the image actually sits in the
   * padded scene canvas so walls/lights target the visible map, not
   * the padding. Omitted on modules that predate the addition; omitted
   * when no scene is active (even on up-to-date modules).
   */
  readonly sceneDimensions?: SceneDimensions | null;
  /**
   * V2 Phase 4 — Module-Aware Napoleon. Compact summaries of the
   * Foundry world's actors, scenes, journals, items, and installed
   * modules so Napoleon can reference existing content by NAME instead
   * of hallucinating duplicates. Populated by the module on every
   * `client.query` when a Foundry session is connected; null/omitted
   * for non-Foundry callers (dashboard chat, etc.). See WorldContent
   * for the full shape.
   */
  readonly worldContent?: WorldContent | null;
  /** IDs of actors currently selected by the GM. */
  readonly selectedActorIds: readonly string[];
  /** Whether the combat tracker is open and in an active combat. */
  readonly inCombat: boolean;
  /**
   * Recent chat messages the backend may use as context for NPC dialogue or
   * mid-session note-taking. Tier 1 passes an empty array; Tier 2 starts
   * populating it with the last N messages.
   */
  readonly recentChat: readonly string[];
}

/**
 * Optional canvas snapshot attached to a `client.query`. The module captures
 * the current viewport of `canvas.stage` when a scene is active and the
 * backend's current model supports image input. Backend-side gating (via
 * `providers.config.ts::modelFlags.supportsImageInput`) discards the
 * snapshot if the active model can't consume it — the module currently
 * sends optimistically.
 *
 * The capture is the GM's current viewport, NOT the full scene — if the
 * GM has panned to a corner, that's what the LLM sees. Reset pan/zoom
 * before querying for full-scene context.
 *
 * Stored by the backend via `captures.ts` with `provenance='user_captured'`,
 * `share_scope='org'` by default (party visibility for tactical snapshots).
 * 5-min signed URL TTL.
 */
export interface ClientQuerySnapshot {
  /** Full data URL: `data:image/jpeg;base64,...`. JPEG default for size, PNG available. */
  readonly dataUrl: string;
  /** Pixel dimensions of the captured viewport. */
  readonly width: number;
  readonly height: number;
  /** Scene's grid cell size in pixels. Lets the backend map px → grid for placement. */
  readonly gridSize: number;
  /** The scene the snapshot was taken from. */
  readonly sceneId: string;
  /** GM-friendly scene name for log + cache key context. */
  readonly sceneName: string;
}

/**
 * Categories used under `Data/worlds/<world>/napoleon/<category>/` for
 * persisted Foundry world data (Phase B.4). Bounded set — if the GM has
 * content that doesn't fit the named slots, it goes in `gm/` as a
 * catch-all. Napoleon browses this tree via `worldFiles` on every query.
 */
export const WORLD_FILE_CATEGORIES = [
  "npcs",
  "scenes",
  "maps",
  "items",
  "journals",
  "gm",
] as const;
export type WorldFileCategory = (typeof WORLD_FILE_CATEGORIES)[number];

/**
 * Metadata about a single file the module discovered under
 * `worlds/<world>/napoleon/` via `FilePicker.browse`. Sent alongside
 * `client.query` so Napoleon can reuse existing assets instead of
 * regenerating (the 80/20 "this feels magic" feature). Capped at 1000
 * entries per query — worlds with more get truncated + a warn log.
 */
export interface ClientWorldFile {
  /** Data-relative path, e.g. `"worlds/otari-pub/napoleon/npcs/pippa.png"`. */
  readonly path: string;
  /** Which subfolder the file was found in. */
  readonly category: WorldFileCategory;
  /** Filename without extension, e.g. `"pippa"`. Used as the reuse key. */
  readonly slug: string;
  /** File size in bytes. Informational only. */
  readonly sizeBytes: number;
}

/**
 * Payload for `client.query`. The module sends this when the GM types
 * `/napoleon <query>` in Foundry chat. The relay forwards it to the AI
 * backend, which responds with zero or more `backend.*` command messages.
 */
export interface ClientQueryPayload {
  /**
   * Stable identifier for this GM's Foundry session. Derived from the
   * `worldId` + `gmUserId` combination at `client.hello` time and reused
   * across every query in the same connection. The backend uses this to
   * maintain conversation context across multiple turns.
   */
  readonly sessionId: string;
  /** The raw text the GM typed after `/napoleon`. */
  readonly query: string;
  /** Optional structured Foundry state at query time. */
  readonly context: QueryContext;
  /**
   * Optional viewport snapshot for vision-capable LLMs. Included when
   * `canvas.scene` is active AND the module has reason to believe the
   * active model can consume images. Backend discards silently if the
   * resolved model does not support image input.
   */
  readonly snapshot?: ClientQuerySnapshot;
  /**
   * Existing Foundry Data files under `worlds/<world>/napoleon/` so
   * Napoleon can reuse them before generating new content. Discovered
   * by the module via `FilePicker.browse` at send time. Capped at
   * 1000 entries; module truncates beyond that and warns in its log.
   */
  readonly worldFiles?: readonly ClientWorldFile[];
}

/**
 * The chat message type enumeration, matching Foundry's `CONST.CHAT_MESSAGE_TYPES`.
 * - `ic`: in-character speech, styled as dialogue
 * - `ooc`: out-of-character, styled as narration
 * - `whisper`: visible only to users in `whisperTo`
 * - `emote`: italicized action description
 */
export type ChatMessageType = "ic" | "ooc" | "whisper" | "emote";

/**
 * Payload for `backend.chat.create`. The backend sends this to inject a
 * chat message into the Foundry chat log. The module renders it via
 * `ChatMessage.create()`.
 */
export interface BackendChatCreatePayload {
  /**
   * The message ID of the client.query that this response answers, if any.
   * When set, the module uses this to find a placeholder "thinking..."
   * message (if one was created when the query was sent) and replace it
   * with the real response.
   */
  readonly correlationId: string | null;
  /** Speaker information rendered as the chat message header. */
  readonly speaker: {
    /** Display name, e.g. "Napoleon" or "Sister Pallid Maren". */
    readonly alias?: string;
    /** Optional existing actor ID to speak through. */
    readonly actorId?: string;
  };
  /** HTML content of the message body. */
  readonly content: string;
  /** Chat message type — determines styling and behavior. */
  readonly type: ChatMessageType;
  /**
   * User IDs to whisper to. Empty array means GM-visible only. Only used
   * when `type === "whisper"`.
   */
  readonly whisperTo: readonly string[];
  /** Optional italic flavor text shown above the content. */
  readonly flavor?: string;
}

/**
 * Payload for `backend.actor.create`. The backend sends this to drop a
 * generated NPC into the Actors sidebar. The module validates the `actor`
 * field against the pf2e-npc-v1 schema before calling `Actor.create()`.
 */
export interface BackendActorCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /**
   * The full Foundry Actor document JSON. The module validates this
   * against `pf2e-npc-v1.schema.json` before creating the actor.
   */
  readonly actor: Readonly<Record<string, unknown>>;
  /** Optional folder ID to place the new actor in. */
  readonly folderId?: string;
}

/**
 * Payload for `backend.actor.update`. The backend sends this to update
 * an existing Actor's fields — most commonly to assign a portrait image
 * or token art after image generation.
 */
export interface BackendActorUpdatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Exact name of the actor to update (case-sensitive). */
  readonly actorName: string;
  /** Partial Actor document — only the fields to change. */
  readonly updates: Readonly<Record<string, unknown>>;
}

/**
 * Payload for `backend.rolltable.create`. The backend sends this to
 * create a RollTable document in the Foundry sidebar.
 */
export interface BackendRollTableCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** RollTable name. */
  readonly name: string;
  /** Dice formula, e.g. "1d20". */
  readonly formula: string;
  /** Table results with text, range, and optional weight. */
  readonly results: ReadonlyArray<{
    readonly text: string;
    readonly range: readonly [number, number];
    readonly weight?: number;
  }>;
}

/**
 * Payload for `backend.token.create`. The backend sends this to place
 * a token of an existing Actor onto a Scene — typically after NPC
 * creation when the GM asked to "spawn" or "place" them on the map.
 * Coordinates default to grid cells (easier for an LLM to reason about:
 * "put the goblin at grid 5,3" maps cleanly to the tactical layout).
 * Coordinates in pixels are supported via coordMode: "px" for cases
 * where the caller already has precise placement data.
 *
 * Defaults:
 *   - sceneId omitted → place on the currently active scene
 *   - coordMode omitted → "grid" (convert via scene.grid.size)
 *   - disposition omitted → 0 (neutral)
 *   - hidden omitted → false (visible to players)
 */
export interface BackendTokenCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Name of the Actor to spawn a token of (must already exist in Foundry's Actors sidebar). */
  readonly actorName: string;
  /** X coordinate (grid cell if coordMode is "grid", pixels if "px"). */
  readonly x: number;
  /** Y coordinate (grid cell if coordMode is "grid", pixels if "px"). */
  readonly y: number;
  /** Coordinate interpretation. Default: "grid". */
  readonly coordMode?: "grid" | "px";
  /** Target scene ID. Default: currently active scene. */
  readonly sceneId?: string;
  /** Token disposition: -1 hostile, 0 neutral, 1 friendly. Default: 0. */
  readonly disposition?: -1 | 0 | 1;
  /** If true, token is hidden from players on placement. Default: false. */
  readonly hidden?: boolean;
}

/**
 * Payload for `backend.scene.create`. The backend sends this to create
 * a Scene document — typically after generating a map image with
 * `image_generate`. Phase B.1 defaults are deliberately minimal: no
 * vision rules, no fog, global light on, no walls/lights/tokens. GMs
 * get a usable scene with zero manual configuration. Phase C+ will
 * layer vision/fog/walls on top as capabilities mature.
 */
export interface BackendSceneCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Scene title shown in the nav bar. */
  readonly name: string;
  /** Public HTTPS URL for the scene's background image (typically a signed Barn URL). */
  readonly img: string;
  /** Scene canvas width in pixels. Typically matches the generated image's width. */
  readonly width: number;
  /** Scene canvas height in pixels. Typically matches the generated image's height. */
  readonly height: number;
  /** Grid cell size in pixels. Default: 100. */
  readonly gridSize?: number;
  /** In-game distance represented by one grid cell. Default: 5 (PF2e ft). */
  readonly gridDistance?: number;
  /** Unit label for grid distance. Default: "ft". */
  readonly gridUnits?: string;
  /** Show the scene in the nav bar. Default: true. */
  readonly navigation?: boolean;
  /** Activate (view) the scene immediately after creation. Default: true. */
  readonly openAfterCreate?: boolean;
}

/**
 * Payload for `backend.wall.create` (V2 Phase 3). The backend sends this
 * to place a single wall segment on a Scene — typically as part of a
 * batch emitted during adventure import or scene-blueprint enrichment.
 * Coordinates are scene pixels (NOT grid cells), matching Foundry's
 * internal Wall document shape.
 *
 * Defaults (if the flag is omitted):
 *   - move: 1 (blocks movement)
 *   - sense: 1 (blocks line-of-sight)
 *   - sound: 0 (pass-through)
 *   - door: 0 (plain wall, not a door)
 *   - sceneName omitted → module uses the currently-active scene
 *
 * Doors (door > 0) still carry their own move/sense/sound flags so the
 * backend can emit a "secret door that blocks sound" if it wants.
 */
export interface BackendWallCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /**
   * Endpoint coordinates [x1, y1, x2, y2]. Interpretation depends on
   * `coordMode`: "image" (default) = image-local pixels with (0,0) at
   * the visible image's top-left; module adds sceneX/sceneY offset.
   * "scene" = raw absolute scene pixels including padding; module
   * passes through unchanged.
   */
  readonly c: readonly [number, number, number, number];
  /** Movement restriction: 0 = pass-through, 1 = blocks movement. */
  readonly move: number;
  /** Line-of-sight restriction: 0 = see-through, 1 = blocks vision. */
  readonly sense: number;
  /** Sound propagation: 0 = pass-through, 1 = blocks sound. */
  readonly sound: number;
  /** Door type: 0 = plain wall, 1 = door, 2 = secret door. */
  readonly door: number;
  /**
   * Coordinate space for `c`. Default "image" — module adds the
   * scene's image offset (`scene.dimensions.sceneX/sceneY`) before
   * creating the Wall document, so Napoleon can reason about walls
   * in image-local space without doing offset math. "scene" passes
   * coords through unchanged (padding-inclusive absolute pixels).
   */
  readonly coordMode?: "image" | "scene";
  /** Target scene name (as given to `backend.scene.create`). Optional — default: active scene. */
  readonly sceneName?: string;
}

/**
 * Payload for `backend.light.create` (V2 Phase 3). Places an AmbientLight
 * embedded document on a scene. Coordinates are scene pixels. `bright`
 * is the inner fully-lit radius; `dim` is the outer dim-light radius
 * (must be >= bright). `angle` defaults to 360 (omnidirectional); set
 * smaller for a directional lantern and use `rotation` to aim it.
 *
 * Light only produces visible effect when the scene's globalLight is
 * off — the adventure importer typically emits `backend.scene.update`
 * with globalLight=false alongside a batch of `backend.light.create`.
 */
export interface BackendLightCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Light position X. Interpretation depends on coordMode (default "image"). */
  readonly x: number;
  /** Light position Y. Interpretation depends on coordMode (default "image"). */
  readonly y: number;
  /** Outer dim-light radius in pixels (unit-less; no offset transform). Must be >= bright. */
  readonly dim: number;
  /** Inner bright-light radius in pixels (fully lit). */
  readonly bright: number;
  /** Cone angle in degrees (0-360). Default: 360 (omnidirectional). */
  readonly angle?: number;
  /** Cone rotation in degrees, meaningful when angle < 360. Default: 0. */
  readonly rotation?: number;
  /** Hex color string (e.g. "#ff8800"). Default/null: Foundry's white. */
  readonly color?: string | null;
  /**
   * Coordinate space for `x, y`. Default "image" — module adds
   * sceneX/sceneY offset. "scene" = raw absolute scene pixels. See
   * BackendWallCreatePayload.coordMode for the full convention.
   */
  readonly coordMode?: "image" | "scene";
  /** Target scene name. Optional — default: active scene. */
  readonly sceneName?: string;
}

/**
 * Payload for `backend.scene.update` (V2 Phase 3). Targets an existing
 * scene and applies any subset of the optional fields; omitted fields
 * are left untouched.
 *
 * Fields use the backend's snake-tolerant camelCase shape; the module's
 * handler maps to Foundry V13's actual document paths — most notably
 * `darkness` → `environment.darknessLevel` and `globalLight` →
 * `environment.globalLight.enabled`. Getting that nesting wrong
 * produces a silent no-op rather than a thrown error (Foundry drops
 * unknown keys without complaint), which is why this payload's shape
 * is deliberately narrow: one field per knob, all optional, so the
 * handler's mapping is an obvious 1:1.
 *
 * Typical use: after `backend.scene.create` (which ships flat-lit
 * defaults) + a batch of `backend.wall.create` / `backend.light.create`,
 * emit a scene.update with globalLight=false + tokenVision=true to
 * activate the vision system the walls gate.
 */
export interface BackendSceneUpdatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Target scene name. Optional — default: active scene. */
  readonly sceneName?: string;
  /** Whether the scene is globally lit (ignoring light sources). */
  readonly globalLight?: boolean;
  /** Darkness level 0.0 (full daylight) to 1.0 (pitch black). */
  readonly darkness?: number;
  /** Whether token-based vision is enforced (false = all tokens see everything). */
  readonly tokenVision?: boolean;
  /** Grid cell size in pixels. */
  readonly gridSize?: number;
  /** In-game distance per grid cell. */
  readonly gridDistance?: number;
  /** Unit label for grid distance. */
  readonly gridUnits?: string;
  /** Show the scene in the nav bar. */
  readonly navigation?: boolean;
}

/**
 * A single page in a `backend.journal.create` message. Tier 1 supports
 * text pages only; Tier 2 adds image, PDF, and video pages.
 */
export interface JournalPageCreate {
  /** Page title. */
  readonly name: string;
  /** Page type. Tier 1: always "text". */
  readonly type: "text";
  /** Page content. */
  readonly text: {
    /** HTML body. */
    readonly content: string;
    /** Foundry page format enum. 1 = HTML. */
    readonly format: 1;
  };
}

/**
 * Payload for `backend.journal.create`. The backend sends this to drop a
 * generated journal entry (scene outline, lore document, handout) into the
 * Journal sidebar.
 */
export interface BackendJournalCreatePayload {
  /** The message ID of the originating client.query, if any. */
  readonly correlationId: string | null;
  /** Journal entry title. */
  readonly name: string;
  /** One or more pages. Tier 1 supports text pages only. */
  readonly pages: readonly JournalPageCreate[];
  /** Optional folder ID to place the new journal entry in. */
  readonly folderId?: string;
}

// ============================================================================
// Phase B.4 — Data persistence (Barn → Foundry Data cache)
// ============================================================================

/**
 * A backend.* command that the module should execute AFTER a successful
 * `backend.data.upload`. Typically the entity-create/update that needed
 * the newly-persisted Data path as its `img` field. The module rewrites
 * the `img` field (or equivalent) to the upload target before dispatching.
 *
 * NOT a full protocol envelope — just (kind, payload). The outer
 * BackendDataUploadMessage provides the envelope fields (v/id/ts).
 */
export type BackendFollowUpCommand =
  | { readonly kind: "backend.chat.create"; readonly payload: BackendChatCreatePayload }
  | { readonly kind: "backend.actor.create"; readonly payload: BackendActorCreatePayload }
  | { readonly kind: "backend.actor.update"; readonly payload: BackendActorUpdatePayload }
  | { readonly kind: "backend.journal.create"; readonly payload: BackendJournalCreatePayload }
  | { readonly kind: "backend.rolltable.create"; readonly payload: BackendRollTableCreatePayload }
  | { readonly kind: "backend.scene.create"; readonly payload: BackendSceneCreatePayload }
  | { readonly kind: "backend.token.create"; readonly payload: BackendTokenCreatePayload };

/**
 * Payload for `backend.data.upload`. Backend sends this when the GM clicks
 * a "Save to World" button — the module fetches the signed URL bytes and
 * uploads them to Foundry's Data directory at `targetPath`, then (if
 * `followUp` is present) dispatches the follow-up command with `img`
 * rewritten to the Data-relative path.
 *
 * Replace-existing collision handling: the module pre-checks the target
 * path with `FilePicker.browse` and emits a `ui.notifications.info` if
 * an existing file is being replaced. No versioning / auto-append. See
 * `local/specs/FOUNDRY-DATA-PERSISTENCE-RFC.md §4` for the rationale.
 */
export interface BackendDataUploadPayload {
  readonly correlationId: string | null;
  /** Short-lived signed Barn URL the module fetches to get the bytes. 5-min TTL typical. */
  readonly signedUrl: string;
  /** Destination path inside Foundry Data, e.g. `"worlds/otari-pub/napoleon/npcs/pippa.png"`. */
  readonly targetPath: string;
  /**
   * Optional command to execute after successful upload. Module rewrites
   * the `img` field (or `src` for journal pages) to `targetPath` before
   * dispatching. On upload failure the follow-up is NOT executed — the
   * GM gets a notification error and the chat preview button stays
   * available for retry (see Q4 in the RFC).
   */
  readonly followUp?: BackendFollowUpCommand;
}

/**
 * Payload for `client.world_save_request`. Module sends this when the GM
 * clicks a "Save to World" button in chat. The relay forwards it to the
 * backend's `/my/foundry/world-save` endpoint (supplying session fields
 * the module doesn't have — worldId, identityId, sessionId come from
 * the authenticated relay connection state), then pushes each returned
 * command back as a separate protocol message. From the module's
 * perspective: send once, let the normal handler dispatch process the
 * incoming `backend.data.upload` (+ any follow-up).
 *
 * See `local/specs/FOUNDRY-DATA-PERSISTENCE-RFC.md §7` (corrected
 * 2026-04-20) for the full rationale — the original direct-POST
 * approach would have required opening the backend endpoint to
 * dv-API-key auth with subdomain CORS complexity.
 */
export interface ClientWorldSaveRequestPayload {
  /** Optional — message ID of the originating client.query, if any. */
  readonly correlationId?: string;
  /** Stable session identifier (same value the module passes on client.query). */
  readonly sessionId: string;
  /** Barn-relative path of the source file (e.g. `"outputs/generated/xxx.png"`). */
  readonly barnPath: string;
  /** Target subfolder under `worlds/<world>/napoleon/`. */
  readonly category: WorldFileCategory;
  /** kebab-case filename without extension. Must match `/^[a-z0-9]+(-[a-z0-9]+)*$/`. */
  readonly slug: string;
  /** What kind of Foundry entity the upload will be applied to (or `save_only` for pure library add). */
  readonly targetType: "actor" | "scene" | "token" | "journal" | "save_only";
  /** Whether the follow-up creates a new entity or updates an existing one. Ignored for `save_only`. */
  readonly targetAction: "create" | "update";
  /** Parameters for the follow-up command; shape varies per targetType. Omit for save_only. */
  readonly params?: Readonly<Record<string, unknown>>;
}

/**
 * Payload for `client.data_upload_ack`. Telemetry ping emitted by the
 * module after attempting a `backend.data.upload`. Backend logs it for
 * observability + failure-rate dashboards; no branching logic depends
 * on it. On `ok: false` the GM has already seen a `ui.notifications.error`
 * locally — the backend doesn't need to act.
 */
export interface ClientDataUploadAckPayload {
  readonly correlationId: string | null;
  readonly targetPath: string;
  readonly ok: boolean;
  /** Short human-readable failure reason when `ok: false`. Absent when `ok: true`. */
  readonly error?: string;
}

/**
 * The type of notable session event captured by the module's auto-capture
 * hook. The relay buffers these and flushes them to the backend in batches
 * for Trough persistence.
 */
export type SessionEventType =
  | "roll"
  | "napoleon_exchange"
  | "combat"
  | "gm_whisper";

/**
 * Payload for `client.session_event`. The module sends this when a notable
 * event occurs during the Foundry session (GM dice rolls, Napoleon
 * exchanges, combat events, GM whispers). The relay buffers these and
 * periodically flushes them to the backend for Trough persistence.
 */
export interface SessionEventPayload {
  /** What kind of notable event this is. */
  readonly eventType: SessionEventType;
  /** Unix epoch ms from the Foundry chat message timestamp. */
  readonly timestamp: number;
  /** Display name of the speaker. */
  readonly speaker: string;
  /** Plain text summary (HTML stripped, max ~500 chars). */
  readonly content: string;
  /** Foundry world state at event time. */
  readonly metadata: {
    readonly worldId: string;
    readonly sceneId?: string;
    readonly combatRound?: number;
  };
}

/**
 * Payload for `ping`. Empty in protocol v1 — the envelope's `id` and `ts`
 * carry everything needed for round-trip latency measurement.
 */
export type PingPayload = Readonly<Record<string, never>>;

/**
 * Payload for `pong`. Echoes the ID of the ping being answered so the
 * sender can correlate and measure latency accurately.
 */
export interface PongPayload {
  /** The `id` of the ping this pong answers. */
  readonly pingId: string;
}

/**
 * Payload for `error`. Sent by either side to report a structured error.
 * The relay uses this to forward validation failures and auth errors back
 * to the client; the client uses it to report local errors (e.g. a failed
 * Actor.create call) back to the backend for logging.
 */
export interface ErrorPayload {
  /** The stable error code. */
  readonly code: ErrorCode;
  /** Human-readable error message (not user-facing). */
  readonly message: string;
  /**
   * The `id` of the message that caused this error, if any. Allows the
   * receiver to correlate the error with the original request.
   */
  readonly correlationId?: string;
}

// ============================================================================
// Discriminated message union
// ============================================================================

/** `client.hello` — module → relay, sent on connect. */
export type ClientHelloMessage = BaseMessage<"client.hello", ClientHelloPayload>;
/** `relay.welcome` — relay → module, response to hello. */
export type RelayWelcomeMessage = BaseMessage<"relay.welcome", RelayWelcomePayload>;
/** `client.query` — module → relay → backend, GM typed `/napoleon ...`. */
export type ClientQueryMessage = BaseMessage<"client.query", ClientQueryPayload>;
/** `client.session_event` — module → relay, auto-captured notable session event. */
export type ClientSessionEventMessage = BaseMessage<"client.session_event", SessionEventPayload>;
/** `backend.chat.create` — backend → relay → module, inject chat message. */
export type BackendChatCreateMessage = BaseMessage<"backend.chat.create", BackendChatCreatePayload>;
/** `backend.actor.create` — backend → relay → module, drop NPC into sidebar. */
export type BackendActorCreateMessage = BaseMessage<"backend.actor.create", BackendActorCreatePayload>;
/** `backend.actor.update` — backend → relay → module, update existing actor fields. */
export type BackendActorUpdateMessage = BaseMessage<"backend.actor.update", BackendActorUpdatePayload>;
/** `backend.journal.create` — backend → relay → module, drop journal entry. */
export type BackendJournalCreateMessage = BaseMessage<"backend.journal.create", BackendJournalCreatePayload>;
/** `backend.rolltable.create` — backend → relay → module, create roll table. */
export type BackendRollTableCreateMessage = BaseMessage<"backend.rolltable.create", BackendRollTableCreatePayload>;
/** `backend.scene.create` — backend → relay → module, create scene with background map image. */
export type BackendSceneCreateMessage = BaseMessage<"backend.scene.create", BackendSceneCreatePayload>;
/** `backend.token.create` — backend → relay → module, place an actor's token on a scene. */
export type BackendTokenCreateMessage = BaseMessage<"backend.token.create", BackendTokenCreatePayload>;
/** `backend.wall.create` — backend → relay → module, place a wall segment on a scene (V2 Phase 3). */
export type BackendWallCreateMessage = BaseMessage<"backend.wall.create", BackendWallCreatePayload>;
/** `backend.light.create` — backend → relay → module, place an ambient light on a scene (V2 Phase 3). */
export type BackendLightCreateMessage = BaseMessage<"backend.light.create", BackendLightCreatePayload>;
/** `backend.scene.update` — backend → relay → module, apply scene-level setting changes (V2 Phase 3). */
export type BackendSceneUpdateMessage = BaseMessage<"backend.scene.update", BackendSceneUpdatePayload>;
/** `backend.data.upload` — backend → relay → module, persist Barn file into Foundry Data (+ optional follow-up). */
export type BackendDataUploadMessage = BaseMessage<"backend.data.upload", BackendDataUploadPayload>;
/** `client.data_upload_ack` — module → relay → backend, telemetry for a data.upload outcome. */
export type ClientDataUploadAckMessage = BaseMessage<"client.data_upload_ack", ClientDataUploadAckPayload>;
/** `client.world_save_request` — module → relay, triggers Barn→Data persist pipeline (relay forwards to backend HTTP). */
export type ClientWorldSaveRequestMessage = BaseMessage<"client.world_save_request", ClientWorldSaveRequestPayload>;
/** `ping` — both directions, keep-alive probe. */
export type PingMessage = BaseMessage<"ping", PingPayload>;
/** `pong` — both directions, response to ping. */
export type PongMessage = BaseMessage<"pong", PongPayload>;
/** `error` — both directions, structured error report. */
export type ErrorMessage = BaseMessage<"error", ErrorPayload>;

/**
 * The full protocol message union. Use `switch (msg.kind)` to narrow to a
 * specific variant with type-safe payload access.
 */
export type ProtocolMessage =
  | ClientHelloMessage
  | RelayWelcomeMessage
  | ClientQueryMessage
  | ClientSessionEventMessage
  | BackendChatCreateMessage
  | BackendActorCreateMessage
  | BackendActorUpdateMessage
  | BackendJournalCreateMessage
  | BackendRollTableCreateMessage
  | BackendSceneCreateMessage
  | BackendSceneUpdateMessage
  | BackendTokenCreateMessage
  | BackendWallCreateMessage
  | BackendLightCreateMessage
  | BackendDataUploadMessage
  | ClientDataUploadAckMessage
  | ClientWorldSaveRequestMessage
  | PingMessage
  | PongMessage
  | ErrorMessage;

/**
 * Helper type that extracts the payload type for a given message kind. Used
 * by `makeMessage` to ensure the payload matches the declared kind.
 */
export type PayloadFor<K extends MessageKind> = Extract<
  ProtocolMessage,
  { kind: K }
>["payload"];

// ============================================================================
// Message construction helpers
// ============================================================================

/**
 * Generate a 16-character alphanumeric message ID using a cryptographically
 * strong random source (Web Crypto API, available in Node 18+ and all modern
 * browsers). The ID space is 62^16 ≈ 4.77e28, collision probability is
 * negligible for any realistic session length.
 */
export function makeMessageId(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  let id = "";
  for (let i = 0; i < 16; i++) {
    // Modulo bias is negligible (62 / 256 ≈ 4% per byte, no security impact).
    id += chars[bytes[i]! % 62];
  }
  return id;
}

/**
 * Construct a protocol message with a fresh ID and current timestamp. The
 * generic parameter `K` is narrowed from the `kind` argument, so the
 * `payload` parameter is checked against the correct payload type at
 * compile time.
 *
 * @example
 * const msg = makeMessage("ping", {});
 * const hello = makeMessage("client.hello", {
 *   protocolVersion: PROTOCOL_VERSION,
 *   authToken: "dv-...",           // or shared secret
 *   worldId: "my-world",
 *   gmUserId: "user-123",
 *   isPrimaryGM: true,
 *   moduleVersion: "0.1.0",
 *   capabilities: { ... }
 * });
 */
export function makeMessage<K extends MessageKind>(
  kind: K,
  payload: PayloadFor<K>
): Extract<ProtocolMessage, { kind: K }> {
  const msg = {
    v: PROTOCOL_VERSION,
    id: makeMessageId(),
    ts: Date.now(),
    kind,
    payload,
  };
  // Cast is safe because `kind` narrows `PayloadFor<K>`, so the constructed
  // object satisfies the narrowed union variant by construction.
  return msg as unknown as Extract<ProtocolMessage, { kind: K }>;
}

// ============================================================================
// Runtime validation
// ============================================================================

/**
 * Internal assertion helper. Throws a `ProtocolError` with `validation_failed`
 * if `condition` is false.
 */
function assert(
  condition: unknown,
  field: string,
  expected: string,
  correlationId?: string
): asserts condition {
  if (!condition) {
    throw new ProtocolError(
      "validation_failed",
      `${field}: expected ${expected}`,
      correlationId
    );
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isStringArray(value: unknown): value is readonly string[] {
  return Array.isArray(value) && value.every((v) => typeof v === "string");
}

/**
 * Validate the envelope fields shared by all messages. Throws on failure.
 * Returns the raw message cast to the envelope shape for further validation.
 */
function validateEnvelope(input: unknown): {
  v: ProtocolVersion;
  id: string;
  ts: number;
  kind: MessageKind;
  payload: Record<string, unknown>;
} {
  assert(isPlainObject(input), "message", "an object");
  const raw = input;

  if (raw.v !== PROTOCOL_VERSION) {
    throw new ProtocolError(
      "protocol_mismatch",
      `expected protocol version ${PROTOCOL_VERSION}, got ${String(raw.v)}`,
      typeof raw.id === "string" ? raw.id : undefined
    );
  }

  assert(isNonEmptyString(raw.id), "id", "a non-empty string");
  assert(isFiniteNumber(raw.ts), "ts", "a finite number");
  assert(isNonEmptyString(raw.kind), "kind", "a non-empty string", raw.id);
  assert(isPlainObject(raw.payload), "payload", "an object", raw.id);

  return {
    v: PROTOCOL_VERSION,
    id: raw.id,
    ts: raw.ts,
    kind: raw.kind as MessageKind,
    payload: raw.payload,
  };
}

function validateCapabilities(
  value: unknown,
  correlationId: string
): asserts value is ClientCapabilities {
  assert(isPlainObject(value), "payload.capabilities", "an object", correlationId);
  const c = value;
  assert(typeof c.chatCreate === "boolean", "capabilities.chatCreate", "boolean", correlationId);
  assert(typeof c.actorCreate === "boolean", "capabilities.actorCreate", "boolean", correlationId);
  assert(typeof c.journalCreate === "boolean", "capabilities.journalCreate", "boolean", correlationId);
  assert(isNonEmptyString(c.systemId), "capabilities.systemId", "non-empty string", correlationId);
  assert(isNonEmptyString(c.systemVersion), "capabilities.systemVersion", "non-empty string", correlationId);
  assert(isNonEmptyString(c.foundryVersion), "capabilities.foundryVersion", "non-empty string", correlationId);
}

function validateHelloPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(payload.protocolVersion === PROTOCOL_VERSION, "payload.protocolVersion", `equals ${PROTOCOL_VERSION}`, correlationId);
  assert(isNonEmptyString(payload.authToken), "payload.authToken", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.worldId), "payload.worldId", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.gmUserId), "payload.gmUserId", "non-empty string", correlationId);
  assert(typeof payload.isPrimaryGM === "boolean", "payload.isPrimaryGM", "boolean", correlationId);
  assert(isNonEmptyString(payload.moduleVersion), "payload.moduleVersion", "non-empty string", correlationId);
  validateCapabilities(payload.capabilities, correlationId);
}

function validateWelcomePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(payload.protocolVersion === PROTOCOL_VERSION, "payload.protocolVersion", `equals ${PROTOCOL_VERSION}`, correlationId);
  assert(isNonEmptyString(payload.relayVersion), "payload.relayVersion", "non-empty string", correlationId);
  assert(typeof payload.backendAvailable === "boolean", "payload.backendAvailable", "boolean", correlationId);
  assert(isFiniteNumber(payload.serverTime), "payload.serverTime", "finite number", correlationId);
}

function validateQueryContext(
  value: unknown,
  correlationId: string
): asserts value is QueryContext {
  assert(isPlainObject(value), "payload.context", "an object", correlationId);
  const ctx = value;
  assert(
    ctx.sceneId === null || typeof ctx.sceneId === "string",
    "context.sceneId",
    "string or null",
    correlationId
  );
  // sceneName is optional — older modules don't include it. Accept any
  // string or null when present; reject other types.
  if ("sceneName" in ctx && ctx.sceneName !== undefined) {
    assert(
      ctx.sceneName === null || typeof ctx.sceneName === "string",
      "context.sceneName",
      "string or null when present",
      correlationId
    );
  }
  // sceneDimensions is optional. When present + not null, all 7 numeric
  // fields must be finite. Omitted / null is the no-active-scene case.
  if ("sceneDimensions" in ctx && ctx.sceneDimensions !== undefined && ctx.sceneDimensions !== null) {
    assert(isPlainObject(ctx.sceneDimensions), "context.sceneDimensions", "an object", correlationId);
    const dims = ctx.sceneDimensions;
    for (const field of ["imageX", "imageY", "imageWidth", "imageHeight", "totalWidth", "totalHeight", "gridSize"] as const) {
      assert(
        typeof dims[field] === "number" && Number.isFinite(dims[field] as number),
        `context.sceneDimensions.${field}`,
        "finite number",
        correlationId
      );
    }
  }
  // worldContent is optional (V2 Phase 4). When present + not null, all
  // five summary arrays must exist with the correct entry shapes.
  // Module-side enumeration enforces the per-type soft caps; the
  // protocol layer only checks structure.
  if ("worldContent" in ctx && ctx.worldContent !== undefined && ctx.worldContent !== null) {
    validateWorldContent(ctx.worldContent, correlationId);
  }
  assert(isStringArray(ctx.selectedActorIds), "context.selectedActorIds", "string array", correlationId);
  assert(typeof ctx.inCombat === "boolean", "context.inCombat", "boolean", correlationId);
  assert(isStringArray(ctx.recentChat), "context.recentChat", "string array", correlationId);
}

function validateWorldContent(
  value: unknown,
  correlationId: string
): asserts value is WorldContent {
  assert(isPlainObject(value), "context.worldContent", "an object", correlationId);
  const wc = value;

  assert(Array.isArray(wc.actors), "context.worldContent.actors", "array", correlationId);
  for (let i = 0; i < (wc.actors as unknown[]).length; i++) {
    const a = (wc.actors as unknown[])[i];
    assert(isPlainObject(a), `context.worldContent.actors[${i}]`, "an object", correlationId);
    assert(isNonEmptyString((a as Record<string, unknown>).id), `context.worldContent.actors[${i}].id`, "non-empty string", correlationId);
    assert(isNonEmptyString((a as Record<string, unknown>).name), `context.worldContent.actors[${i}].name`, "non-empty string", correlationId);
    assert(isNonEmptyString((a as Record<string, unknown>).type), `context.worldContent.actors[${i}].type`, "non-empty string", correlationId);
    if ("level" in (a as Record<string, unknown>) && (a as Record<string, unknown>).level !== undefined) {
      assert(
        typeof (a as Record<string, unknown>).level === "number" && Number.isFinite((a as Record<string, unknown>).level as number),
        `context.worldContent.actors[${i}].level`,
        "finite number when present",
        correlationId
      );
    }
    if ("folder" in (a as Record<string, unknown>) && (a as Record<string, unknown>).folder !== undefined) {
      assert(typeof (a as Record<string, unknown>).folder === "string", `context.worldContent.actors[${i}].folder`, "string when present", correlationId);
    }
  }

  assert(Array.isArray(wc.scenes), "context.worldContent.scenes", "array", correlationId);
  for (let i = 0; i < (wc.scenes as unknown[]).length; i++) {
    const s = (wc.scenes as unknown[])[i];
    assert(isPlainObject(s), `context.worldContent.scenes[${i}]`, "an object", correlationId);
    assert(isNonEmptyString((s as Record<string, unknown>).id), `context.worldContent.scenes[${i}].id`, "non-empty string", correlationId);
    assert(isNonEmptyString((s as Record<string, unknown>).name), `context.worldContent.scenes[${i}].name`, "non-empty string", correlationId);
    assert(typeof (s as Record<string, unknown>).active === "boolean", `context.worldContent.scenes[${i}].active`, "boolean", correlationId);
    if ("folder" in (s as Record<string, unknown>) && (s as Record<string, unknown>).folder !== undefined) {
      assert(typeof (s as Record<string, unknown>).folder === "string", `context.worldContent.scenes[${i}].folder`, "string when present", correlationId);
    }
  }

  assert(Array.isArray(wc.journals), "context.worldContent.journals", "array", correlationId);
  for (let i = 0; i < (wc.journals as unknown[]).length; i++) {
    const j = (wc.journals as unknown[])[i];
    assert(isPlainObject(j), `context.worldContent.journals[${i}]`, "an object", correlationId);
    assert(isNonEmptyString((j as Record<string, unknown>).id), `context.worldContent.journals[${i}].id`, "non-empty string", correlationId);
    assert(isNonEmptyString((j as Record<string, unknown>).name), `context.worldContent.journals[${i}].name`, "non-empty string", correlationId);
    if ("folder" in (j as Record<string, unknown>) && (j as Record<string, unknown>).folder !== undefined) {
      assert(typeof (j as Record<string, unknown>).folder === "string", `context.worldContent.journals[${i}].folder`, "string when present", correlationId);
    }
    if ("pageCount" in (j as Record<string, unknown>) && (j as Record<string, unknown>).pageCount !== undefined) {
      assert(
        typeof (j as Record<string, unknown>).pageCount === "number" && Number.isFinite((j as Record<string, unknown>).pageCount as number),
        `context.worldContent.journals[${i}].pageCount`,
        "finite number when present",
        correlationId
      );
    }
  }

  assert(Array.isArray(wc.items), "context.worldContent.items", "array", correlationId);
  for (let i = 0; i < (wc.items as unknown[]).length; i++) {
    const it = (wc.items as unknown[])[i];
    assert(isPlainObject(it), `context.worldContent.items[${i}]`, "an object", correlationId);
    assert(isNonEmptyString((it as Record<string, unknown>).id), `context.worldContent.items[${i}].id`, "non-empty string", correlationId);
    assert(isNonEmptyString((it as Record<string, unknown>).name), `context.worldContent.items[${i}].name`, "non-empty string", correlationId);
    assert(isNonEmptyString((it as Record<string, unknown>).type), `context.worldContent.items[${i}].type`, "non-empty string", correlationId);
    if ("folder" in (it as Record<string, unknown>) && (it as Record<string, unknown>).folder !== undefined) {
      assert(typeof (it as Record<string, unknown>).folder === "string", `context.worldContent.items[${i}].folder`, "string when present", correlationId);
    }
  }

  assert(Array.isArray(wc.modules), "context.worldContent.modules", "array", correlationId);
  for (let i = 0; i < (wc.modules as unknown[]).length; i++) {
    const m = (wc.modules as unknown[])[i];
    assert(isPlainObject(m), `context.worldContent.modules[${i}]`, "an object", correlationId);
    assert(isNonEmptyString((m as Record<string, unknown>).id), `context.worldContent.modules[${i}].id`, "non-empty string", correlationId);
    assert(isNonEmptyString((m as Record<string, unknown>).title), `context.worldContent.modules[${i}].title`, "non-empty string", correlationId);
    assert(typeof (m as Record<string, unknown>).active === "boolean", `context.worldContent.modules[${i}].active`, "boolean", correlationId);
  }
}

function validateQuerySnapshot(
  value: unknown,
  correlationId: string
): asserts value is ClientQuerySnapshot {
  assert(isPlainObject(value), "payload.snapshot", "an object", correlationId);
  const snap = value;
  assert(isNonEmptyString(snap.dataUrl), "snapshot.dataUrl", "non-empty string", correlationId);
  assert(
    typeof snap.dataUrl === "string" && snap.dataUrl.startsWith("data:image/"),
    "snapshot.dataUrl",
    "data URL with image/ media type",
    correlationId
  );
  assert(typeof snap.width === "number" && snap.width > 0, "snapshot.width", "positive number", correlationId);
  assert(typeof snap.height === "number" && snap.height > 0, "snapshot.height", "positive number", correlationId);
  assert(typeof snap.gridSize === "number" && snap.gridSize > 0, "snapshot.gridSize", "positive number", correlationId);
  assert(isNonEmptyString(snap.sceneId), "snapshot.sceneId", "non-empty string", correlationId);
  assert(isNonEmptyString(snap.sceneName), "snapshot.sceneName", "non-empty string", correlationId);
}

const VALID_WORLD_FILE_CATEGORIES = new Set<string>(WORLD_FILE_CATEGORIES);

function validateWorldFiles(
  value: unknown,
  correlationId: string
): asserts value is readonly ClientWorldFile[] {
  assert(Array.isArray(value), "payload.worldFiles", "array", correlationId);
  assert(
    value.length <= 1000,
    "payload.worldFiles.length",
    "<= 1000 (module truncates beyond this)",
    correlationId
  );
  for (let i = 0; i < value.length; i++) {
    const f = value[i];
    assert(isPlainObject(f), `worldFiles[${i}]`, "an object", correlationId);
    assert(isNonEmptyString(f.path), `worldFiles[${i}].path`, "non-empty string", correlationId);
    assert(
      typeof f.category === "string" && VALID_WORLD_FILE_CATEGORIES.has(f.category),
      `worldFiles[${i}].category`,
      "one of npcs|scenes|maps|items|journals|gm",
      correlationId
    );
    assert(isNonEmptyString(f.slug), `worldFiles[${i}].slug`, "non-empty string", correlationId);
    assert(
      typeof f.sizeBytes === "number" && f.sizeBytes >= 0,
      `worldFiles[${i}].sizeBytes`,
      "non-negative number",
      correlationId
    );
  }
}

function validateQueryPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(isNonEmptyString(payload.sessionId), "payload.sessionId", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.query), "payload.query", "non-empty string", correlationId);
  validateQueryContext(payload.context, correlationId);
  if (payload.snapshot !== undefined) {
    validateQuerySnapshot(payload.snapshot, correlationId);
  }
  if (payload.worldFiles !== undefined) {
    validateWorldFiles(payload.worldFiles, correlationId);
  }
}

function validateChatCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isPlainObject(payload.speaker), "payload.speaker", "an object", correlationId);
  const speaker = payload.speaker;
  if ("alias" in speaker) {
    assert(typeof speaker.alias === "string", "speaker.alias", "string when present", correlationId);
  }
  if ("actorId" in speaker) {
    assert(typeof speaker.actorId === "string", "speaker.actorId", "string when present", correlationId);
  }
  assert(isNonEmptyString(payload.content), "payload.content", "non-empty string", correlationId);
  assert(
    payload.type === "ic" ||
      payload.type === "ooc" ||
      payload.type === "whisper" ||
      payload.type === "emote",
    "payload.type",
    "one of ic|ooc|whisper|emote",
    correlationId
  );
  assert(isStringArray(payload.whisperTo), "payload.whisperTo", "string array", correlationId);
  if ("flavor" in payload) {
    assert(typeof payload.flavor === "string", "payload.flavor", "string when present", correlationId);
  }
}

function validateActorCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isPlainObject(payload.actor), "payload.actor", "an object", correlationId);
  if ("folderId" in payload) {
    assert(typeof payload.folderId === "string", "payload.folderId", "string when present", correlationId);
  }
}

function validateActorUpdatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.actorName), "payload.actorName", "non-empty string", correlationId);
  assert(isPlainObject(payload.updates), "payload.updates", "an object", correlationId);
}

function validateRollTableCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.name), "payload.name", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.formula), "payload.formula", "non-empty string", correlationId);
  assert(Array.isArray(payload.results), "payload.results", "an array", correlationId);
  assert((payload.results as unknown[]).length > 0, "payload.results", "non-empty array", correlationId);
}

function validateTokenCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.actorName), "payload.actorName", "non-empty string", correlationId);
  assert(typeof payload.x === "number" && Number.isFinite(payload.x), "payload.x", "finite number", correlationId);
  assert(typeof payload.y === "number" && Number.isFinite(payload.y), "payload.y", "finite number", correlationId);
  if ("coordMode" in payload) {
    assert(payload.coordMode === "grid" || payload.coordMode === "px", "payload.coordMode", "'grid' or 'px' when present", correlationId);
  }
  if ("sceneId" in payload) {
    assert(typeof payload.sceneId === "string", "payload.sceneId", "string when present", correlationId);
  }
  if ("disposition" in payload) {
    assert(payload.disposition === -1 || payload.disposition === 0 || payload.disposition === 1, "payload.disposition", "-1, 0, or 1 when present", correlationId);
  }
  if ("hidden" in payload) {
    assert(typeof payload.hidden === "boolean", "payload.hidden", "boolean when present", correlationId);
  }
}

function validateSceneCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.name), "payload.name", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.img), "payload.img", "non-empty string", correlationId);
  assert(typeof payload.width === "number" && payload.width > 0, "payload.width", "positive number", correlationId);
  assert(typeof payload.height === "number" && payload.height > 0, "payload.height", "positive number", correlationId);
  if ("gridSize" in payload) {
    assert(typeof payload.gridSize === "number" && payload.gridSize > 0, "payload.gridSize", "positive number when present", correlationId);
  }
  if ("gridDistance" in payload) {
    assert(typeof payload.gridDistance === "number" && payload.gridDistance > 0, "payload.gridDistance", "positive number when present", correlationId);
  }
  if ("gridUnits" in payload) {
    assert(typeof payload.gridUnits === "string", "payload.gridUnits", "string when present", correlationId);
  }
  if ("navigation" in payload) {
    assert(typeof payload.navigation === "boolean", "payload.navigation", "boolean when present", correlationId);
  }
  if ("openAfterCreate" in payload) {
    assert(typeof payload.openAfterCreate === "boolean", "payload.openAfterCreate", "boolean when present", correlationId);
  }
}

function validateWallCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(Array.isArray(payload.c), "payload.c", "array of 4 numbers", correlationId);
  const c = payload.c as unknown[];
  assert(c.length === 4, "payload.c", "array of exactly 4 numbers", correlationId);
  for (let i = 0; i < 4; i++) {
    assert(
      typeof c[i] === "number" && Number.isFinite(c[i] as number),
      `payload.c[${i}]`,
      "finite number",
      correlationId
    );
  }
  for (const flag of ["move", "sense", "sound", "door"] as const) {
    assert(
      typeof payload[flag] === "number" && Number.isInteger(payload[flag]) && (payload[flag] as number) >= 0,
      `payload.${flag}`,
      "non-negative integer",
      correlationId
    );
  }
  // Sanity bounds — Foundry's actual flags are 0/1 (or 0/1/2 for door);
  // anything higher is meaningless. Reject early so a malformed backend
  // doesn't bloat scene documents with junk values.
  assert((payload.move as number) <= 1, "payload.move", "0 or 1", correlationId);
  assert((payload.sense as number) <= 1, "payload.sense", "0 or 1", correlationId);
  assert((payload.sound as number) <= 1, "payload.sound", "0 or 1", correlationId);
  assert((payload.door as number) <= 2, "payload.door", "0, 1, or 2", correlationId);
  if ("coordMode" in payload && payload.coordMode !== undefined) {
    assert(
      payload.coordMode === "image" || payload.coordMode === "scene",
      "payload.coordMode",
      "'image' or 'scene' when present",
      correlationId
    );
  }
  if ("sceneName" in payload) {
    assert(typeof payload.sceneName === "string", "payload.sceneName", "string when present", correlationId);
  }
}

function validateLightCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  for (const field of ["x", "y", "dim", "bright"] as const) {
    assert(
      typeof payload[field] === "number" && Number.isFinite(payload[field] as number),
      `payload.${field}`,
      "finite number",
      correlationId
    );
  }
  assert((payload.dim as number) >= 0, "payload.dim", "non-negative", correlationId);
  assert((payload.bright as number) >= 0, "payload.bright", "non-negative", correlationId);
  assert(
    (payload.bright as number) <= (payload.dim as number),
    "payload.bright",
    "<= payload.dim (bright is the inner fully-lit radius, dim is the outer dim-light radius)",
    correlationId
  );
  if ("angle" in payload) {
    assert(
      typeof payload.angle === "number" && Number.isFinite(payload.angle) && payload.angle >= 0 && payload.angle <= 360,
      "payload.angle",
      "number in [0, 360]",
      correlationId
    );
  }
  if ("rotation" in payload) {
    assert(
      typeof payload.rotation === "number" && Number.isFinite(payload.rotation),
      "payload.rotation",
      "finite number",
      correlationId
    );
  }
  if ("color" in payload) {
    assert(
      payload.color === null || typeof payload.color === "string",
      "payload.color",
      "string or null when present",
      correlationId
    );
  }
  if ("coordMode" in payload && payload.coordMode !== undefined) {
    assert(
      payload.coordMode === "image" || payload.coordMode === "scene",
      "payload.coordMode",
      "'image' or 'scene' when present",
      correlationId
    );
  }
  if ("sceneName" in payload) {
    assert(typeof payload.sceneName === "string", "payload.sceneName", "string when present", correlationId);
  }
}

function validateSceneUpdatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  if ("sceneName" in payload) {
    assert(typeof payload.sceneName === "string", "payload.sceneName", "string when present", correlationId);
  }
  if ("globalLight" in payload) {
    assert(typeof payload.globalLight === "boolean", "payload.globalLight", "boolean when present", correlationId);
  }
  if ("darkness" in payload) {
    assert(
      typeof payload.darkness === "number" && Number.isFinite(payload.darkness) && payload.darkness >= 0 && payload.darkness <= 1,
      "payload.darkness",
      "number in [0, 1]",
      correlationId
    );
  }
  if ("tokenVision" in payload) {
    assert(typeof payload.tokenVision === "boolean", "payload.tokenVision", "boolean when present", correlationId);
  }
  if ("gridSize" in payload) {
    assert(
      typeof payload.gridSize === "number" && payload.gridSize > 0,
      "payload.gridSize",
      "positive number when present",
      correlationId
    );
  }
  if ("gridDistance" in payload) {
    assert(
      typeof payload.gridDistance === "number" && payload.gridDistance > 0,
      "payload.gridDistance",
      "positive number when present",
      correlationId
    );
  }
  if ("gridUnits" in payload) {
    assert(typeof payload.gridUnits === "string", "payload.gridUnits", "string when present", correlationId);
  }
  if ("navigation" in payload) {
    assert(typeof payload.navigation === "boolean", "payload.navigation", "boolean when present", correlationId);
  }
  // Reject no-op updates — every field missing means the backend emitted
  // a dead command. Self-correcting error instead of a silent no-op.
  const updateKeys = ["globalLight", "darkness", "tokenVision", "gridSize", "gridDistance", "gridUnits", "navigation"];
  const hasUpdate = updateKeys.some((k) => k in payload);
  assert(hasUpdate, "payload", `one of [${updateKeys.join(", ")}] to be present`, correlationId);
}

function validateJournalCreatePayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.name), "payload.name", "non-empty string", correlationId);
  assert(Array.isArray(payload.pages), "payload.pages", "an array", correlationId);
  assert((payload.pages as unknown[]).length > 0, "payload.pages", "non-empty array", correlationId);
  for (const [index, page] of (payload.pages as unknown[]).entries()) {
    assert(isPlainObject(page), `pages[${index}]`, "an object", correlationId);
    const p = page;
    assert(isNonEmptyString(p.name), `pages[${index}].name`, "non-empty string", correlationId);
    assert(p.type === "text", `pages[${index}].type`, `"text"`, correlationId);
    assert(isPlainObject(p.text), `pages[${index}].text`, "an object", correlationId);
    const text = p.text;
    assert(typeof text.content === "string", `pages[${index}].text.content`, "string", correlationId);
    assert(text.format === 1, `pages[${index}].text.format`, "1 (HTML)", correlationId);
  }
  if ("folderId" in payload) {
    assert(typeof payload.folderId === "string", "payload.folderId", "string when present", correlationId);
  }
}

const VALID_SESSION_EVENT_TYPES = new Set<string>([
  "roll",
  "napoleon_exchange",
  "combat",
  "gm_whisper",
]);

function validateSessionEventPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    typeof payload.eventType === "string" && VALID_SESSION_EVENT_TYPES.has(payload.eventType),
    "payload.eventType",
    "one of roll|napoleon_exchange|combat|gm_whisper",
    correlationId
  );
  assert(isFiniteNumber(payload.timestamp), "payload.timestamp", "finite number", correlationId);
  assert(isNonEmptyString(payload.speaker), "payload.speaker", "non-empty string", correlationId);
  assert(typeof payload.content === "string", "payload.content", "string", correlationId);
  assert(isPlainObject(payload.metadata), "payload.metadata", "an object", correlationId);
  const meta = payload.metadata;
  assert(isNonEmptyString(meta.worldId), "metadata.worldId", "non-empty string", correlationId);
  if ("sceneId" in meta) {
    assert(typeof meta.sceneId === "string", "metadata.sceneId", "string when present", correlationId);
  }
  if ("combatRound" in meta) {
    assert(isFiniteNumber(meta.combatRound), "metadata.combatRound", "finite number when present", correlationId);
  }
}

// ── Data upload validators (Phase B.4) ────────────────────────────────

/**
 * Validate a follow-up command nested inside `backend.data.upload`.
 * Dispatches to the same per-kind validators used at the envelope level
 * so we can't construct an invalid follow-up.
 */
function validateFollowUpCommand(
  value: unknown,
  correlationId: string
): asserts value is BackendFollowUpCommand {
  assert(isPlainObject(value), "payload.followUp", "an object", correlationId);
  const f = value;
  assert(isNonEmptyString(f.kind), "followUp.kind", "non-empty string", correlationId);
  assert(isPlainObject(f.payload), "followUp.payload", "an object", correlationId);
  const fp = f.payload as Record<string, unknown>;
  switch (f.kind) {
    case "backend.chat.create":
      validateChatCreatePayload(fp, correlationId);
      break;
    case "backend.actor.create":
      validateActorCreatePayload(fp, correlationId);
      break;
    case "backend.actor.update":
      validateActorUpdatePayload(fp, correlationId);
      break;
    case "backend.journal.create":
      validateJournalCreatePayload(fp, correlationId);
      break;
    case "backend.rolltable.create":
      validateRollTableCreatePayload(fp, correlationId);
      break;
    case "backend.scene.create":
      validateSceneCreatePayload(fp, correlationId);
      break;
    case "backend.token.create":
      validateTokenCreatePayload(fp, correlationId);
      break;
    default:
      throw new ProtocolError(
        "validation_failed",
        `followUp.kind: invalid backend command (got ${String(f.kind)})`,
        correlationId
      );
  }
}

function validateDataUploadPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.signedUrl), "payload.signedUrl", "non-empty string", correlationId);
  assert(
    typeof payload.signedUrl === "string" && /^https?:\/\//.test(payload.signedUrl),
    "payload.signedUrl",
    "http(s) URL",
    correlationId
  );
  assert(isNonEmptyString(payload.targetPath), "payload.targetPath", "non-empty string", correlationId);
  assert(
    typeof payload.targetPath === "string" && payload.targetPath.startsWith("worlds/"),
    "payload.targetPath",
    "starts with 'worlds/' (per §4 path convention)",
    correlationId
  );
  if (payload.followUp !== undefined) {
    validateFollowUpCommand(payload.followUp, correlationId);
  }
}

const SLUG_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const VALID_TARGET_TYPES = new Set<string>(["actor", "scene", "token", "journal", "save_only"]);
const VALID_TARGET_ACTIONS = new Set<string>(["create", "update"]);

function validateWorldSaveRequestPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  if ("correlationId" in payload && payload.correlationId !== undefined) {
    assert(
      typeof payload.correlationId === "string",
      "payload.correlationId",
      "string when present",
      correlationId
    );
  }
  assert(isNonEmptyString(payload.sessionId), "payload.sessionId", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.barnPath), "payload.barnPath", "non-empty string", correlationId);
  assert(
    typeof payload.barnPath === "string" && !payload.barnPath.includes("..") && !payload.barnPath.startsWith("/"),
    "payload.barnPath",
    "Barn-relative path (no leading / and no '..')",
    correlationId
  );
  assert(
    typeof payload.category === "string" && VALID_WORLD_FILE_CATEGORIES.has(payload.category),
    "payload.category",
    "one of npcs|scenes|maps|items|journals|gm",
    correlationId
  );
  assert(
    typeof payload.slug === "string" && SLUG_PATTERN.test(payload.slug),
    "payload.slug",
    "kebab-case string (lowercase, digits, hyphens only)",
    correlationId
  );
  assert(
    typeof payload.targetType === "string" && VALID_TARGET_TYPES.has(payload.targetType),
    "payload.targetType",
    "one of actor|scene|token|journal|save_only",
    correlationId
  );
  assert(
    typeof payload.targetAction === "string" && VALID_TARGET_ACTIONS.has(payload.targetAction),
    "payload.targetAction",
    "one of create|update",
    correlationId
  );
  if ("params" in payload && payload.params !== undefined) {
    assert(isPlainObject(payload.params), "payload.params", "an object when present", correlationId);
  }
}

function validateDataUploadAckPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(
    payload.correlationId === null || typeof payload.correlationId === "string",
    "payload.correlationId",
    "string or null",
    correlationId
  );
  assert(isNonEmptyString(payload.targetPath), "payload.targetPath", "non-empty string", correlationId);
  assert(typeof payload.ok === "boolean", "payload.ok", "boolean", correlationId);
  if ("error" in payload && payload.error !== undefined) {
    assert(typeof payload.error === "string", "payload.error", "string when present", correlationId);
  }
}

function validatePongPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(isNonEmptyString(payload.pingId), "payload.pingId", "non-empty string", correlationId);
}

function validateErrorPayload(
  payload: Record<string, unknown>,
  correlationId: string
): void {
  assert(isNonEmptyString(payload.code), "payload.code", "non-empty string", correlationId);
  assert(isNonEmptyString(payload.message), "payload.message", "non-empty string", correlationId);
  if ("correlationId" in payload) {
    assert(
      typeof payload.correlationId === "string",
      "payload.correlationId",
      "string when present",
      correlationId
    );
  }
}

/**
 * Validate an arbitrary value (usually the result of `JSON.parse()` on a
 * WebSocket frame) against the protocol v1 message contract. Throws a
 * `ProtocolError` with a specific code on failure; returns the input
 * narrowed to `ProtocolMessage` on success.
 *
 * The relay calls this on every inbound frame after JSON parsing. Errors
 * produced by this function are converted by the relay's error handler
 * into outbound `error` messages sent back to the offending client.
 *
 * @throws {ProtocolError} with `code: "validation_failed"` for structural
 *   errors, `"protocol_mismatch"` for version errors, or `"unknown_kind"`
 *   for unknown message kinds.
 */
export function validateMessage(input: unknown): ProtocolMessage {
  const envelope = validateEnvelope(input);
  const { kind, payload, id } = envelope;

  switch (kind) {
    case "client.hello":
      validateHelloPayload(payload, id);
      break;
    case "relay.welcome":
      validateWelcomePayload(payload, id);
      break;
    case "client.query":
      validateQueryPayload(payload, id);
      break;
    case "client.session_event":
      validateSessionEventPayload(payload, id);
      break;
    case "backend.chat.create":
      validateChatCreatePayload(payload, id);
      break;
    case "backend.actor.create":
      validateActorCreatePayload(payload, id);
      break;
    case "backend.actor.update":
      validateActorUpdatePayload(payload, id);
      break;
    case "backend.journal.create":
      validateJournalCreatePayload(payload, id);
      break;
    case "backend.rolltable.create":
      validateRollTableCreatePayload(payload, id);
      break;
    case "backend.scene.create":
      validateSceneCreatePayload(payload, id);
      break;
    case "backend.scene.update":
      validateSceneUpdatePayload(payload, id);
      break;
    case "backend.token.create":
      validateTokenCreatePayload(payload, id);
      break;
    case "backend.wall.create":
      validateWallCreatePayload(payload, id);
      break;
    case "backend.light.create":
      validateLightCreatePayload(payload, id);
      break;
    case "backend.data.upload":
      validateDataUploadPayload(payload, id);
      break;
    case "client.data_upload_ack":
      validateDataUploadAckPayload(payload, id);
      break;
    case "client.world_save_request":
      validateWorldSaveRequestPayload(payload, id);
      break;
    case "ping":
      // PingPayload is empty — no further validation needed.
      break;
    case "pong":
      validatePongPayload(payload, id);
      break;
    case "error":
      validateErrorPayload(payload, id);
      break;
    default: {
      // Exhaustiveness check: if a new MessageKind is added to the union
      // without a case here, TypeScript will fail to compile because `kind`
      // will not be `never`.
      const exhaustive: never = kind;
      throw new ProtocolError(
        "unknown_kind",
        `unknown message kind: ${String(exhaustive)}`,
        id
      );
    }
  }

  return input as ProtocolMessage;
}
